In [1]:
import pandas as pd

In [2]:
func_effects_23 = pd.read_csv('../../results/func_effects/averages/293_2-3_entry_func_effects.csv')
func_effects_23

      site wildtype mutant   effect  effect_std  times_seen  n_selections
0      100        G      A -0.00205      0.9766        3.00             4
1      100        G      C -3.91300      0.0130        8.00             4
2      100        G      D -4.76800      0.0000       20.00             4
3      100        G      E -4.58800      0.0000        1.00             2
4      100        G      F -4.53500      0.1210        1.00             4
...    ...      ...    ...      ...         ...         ...           ...
10272   99        P      S -2.16400      0.8024        6.25             4
10273   99        P      T -1.50300      0.8134        6.50             4
10274   99        P      V -0.74000      0.4864        3.50             4
10275   99        P      W -2.90700      1.1400        2.50             4
10276   99        P      Y -2.26500      0.5205        3.50             4

[10277 rows x 7 columns]

In [3]:
func_effects_26 = pd.read_csv('../../results/func_effects/averages/293_2-6_entry_func_effects.csv')
func_effects_26

      site wildtype mutant  effect  effect_std  times_seen  n_selections
0      100        G      A  -1.319      0.8159        3.00             4
1      100        G      C  -4.422      0.0000        8.00             4
2      100        G      D  -4.937      0.0000       20.00             4
3      100        G      E  -4.745      0.0000        1.00             2
4      100        G      F  -4.719      0.0000        1.00             4
...    ...      ...    ...     ...         ...         ...           ...
10272   99        P      S  -2.903      0.6227        6.25             4
10273   99        P      T  -2.545      0.4738        6.50             4
10274   99        P      V  -1.324      0.6326        3.50             4
10275   99        P      W  -3.612      0.3808        2.50             4
10276   99        P      Y  -3.962      0.1560        3.50             4

[10277 rows x 7 columns]

In [4]:
map = pd.read_csv('site_numbering_map.csv')
map

     sequential_site reference_site sequential_wt region   rbs_region chain
0                  1             11             D    HA1  outside RBS     A
1                  2             12             K    HA1  outside RBS     A
2                  3             13             I    HA1  outside RBS     A
3                  4             14             C    HA1  outside RBS     A
4                  5             15             L    HA1  outside RBS     A
..               ...            ...           ...    ...          ...   ...
501              502            510             G    HA2  outside RBS   NaN
502              503            511             Y    HA2  outside RBS   NaN
503              504            512             K    HA2  outside RBS   NaN
504              505            513             D    HA2  outside RBS   NaN
505              506            514             V    HA2  outside RBS   NaN

[506 rows x 6 columns]

In [5]:
func_effects_ref_23 = pd.merge(
    func_effects_23,
    map,
    left_on=['site'],
    right_on=['reference_site']
)[['sequential_site', 'wildtype', 'mutant', 'effect', 'chain']].rename(
    columns={'sequential_site' : 'site'}
)

func_effects_ref_23.to_csv('2-3_entry_func_effects_sequential.csv')

In [8]:
func_effects_ref_26 = pd.merge(
    func_effects_26,
    map,
    left_on=['site'],
    right_on=['reference_site']
)[['sequential_site', 'wildtype', 'mutant', 'effect', 'chain']].rename(
    columns={'sequential_site' : 'site'}
)

func_effects_ref_26.to_csv('2-6_entry_func_effects_sequential.csv')

In [7]:
stab_effects = pd.read_csv('stability_mut_effect.csv')
stab_effects

,epitope,site,wildtype,mutant,mutation,stability_mean,stability_median,stability_std,n_models,times_seen,frac_models,LibA-250703-pH,LibB-250703-pH
0,1,11,D,A,D11A,-0.427500,-0.427500,0.06077,2,4.5,1.0,-0.36680,-0.48830
1,1,11,D,C,D11C,-0.093440,-0.093440,0.00502,2,3.5,1.0,-0.09847,-0.08842
2,1,11,D,E,D11E,0.048140,0.048140,0.45330,2,1.0,1.0,-0.40520,0.50140
3,1,11,D,F,D11F,-0.936300,-0.936300,0.00000,1,1.0,0.5,NaN,-0.93630
4,1,11,D,G,D11G,-0.378500,-0.378500,0.27140,2,1.5,1.0,-0.64990,-0.10710
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8442,1,514,V,R,V514R,-0.709900,-0.709900,0.00000,1,1.0,0.5,NaN,-0.70990
8443,1,514,V,S,V514S,-0.255200,-0.255200,0.21240,2,2.0,1.0,-0.04275,-0.46760
8444,1,514,V,T,V514T,0.014040,0.014040,0.07515,2,2.0,1.0,0.08919,-0.06110
8445,1,514,V,W,V514W,0.001978,0.001978,0.01991,2,5.5,1.0,0.02188,-0.01793
8446,1,514,V,Y,V514Y,-0.037560,-0.037560,0.07866,2,2.0,1.0,-0.11620,0.04110

In [3]:
map = pd.read_csv('site_numbering_map.csv')
map

     sequential_site reference_site sequential_wt region   rbs_region chain
0                  1             11             D    HA1  outside RBS     A
1                  2             12             K    HA1  outside RBS     A
2                  3             13             I    HA1  outside RBS     A
3                  4             14             C    HA1  outside RBS     A
4                  5             15             L    HA1  outside RBS     A
..               ...            ...           ...    ...          ...   ...
501              502            510             G    HA2  outside RBS   NaN
502              503            511             Y    HA2  outside RBS   NaN
503              504            512             K    HA2  outside RBS   NaN
504              505            513             D    HA2  outside RBS   NaN
505              506            514             V    HA2  outside RBS   NaN

[506 rows x 6 columns]

In [6]:
stab_effects_ref = pd.merge(
    stab_effects,
    map,
    left_on=['site'],
    right_on=['reference_site']
)[[ 'sequential_site', 'wildtype', 'mutant', 'stability_mean', 'chain']].rename(
    columns={'sequential_site' : 'site'}
)

stab_effects_ref.to_csv('mix_entry_stab_effects_sequential.csv')

In [4]:
ab_1A8 = pd.read_csv('../../results/antibody_escape/averages/1A8_mut_effect.csv')
ab_1A8

,epitope,site,wildtype,mutant,mutation,escape_mean,escape_median,escape_std,n_models,times_seen,frac_models,A-251009-H7-mix-1A8,B-251009-H7-mix-1A8
0,1,11,D,A,D11A,0.05735,0.05735,0.11950,2,4.500,1.0,0.17690,-0.062190
1,1,11,D,C,D11C,0.07810,0.07810,0.17310,2,3.500,1.0,0.25120,-0.095030
2,1,11,D,E,D11E,0.05503,0.05503,0.13110,2,1.000,1.0,0.18610,-0.076040
3,1,11,D,F,D11F,0.03457,0.03457,0.06047,2,1.000,1.0,0.09504,-0.025900
4,1,11,D,G,D11G,0.73710,0.73710,0.99650,2,2.667,1.0,1.73400,-0.259400
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8883,1,514,V,R,V514R,0.38300,0.38300,0.00000,1,3.000,0.5,0.38300,NaN
8884,1,514,V,S,V514S,0.02457,0.02457,0.10810,2,1.500,1.0,0.13260,-0.083510
8885,1,514,V,T,V514T,-0.04257,-0.04257,0.02216,2,2.500,1.0,-0.06473,-0.020410
8886,1,514,V,W,V514W,-0.19850,-0.19850,0.15700,2,5.500,1.0,-0.35550,-0.041510
8887,1,514,V,Y,V514Y,-0.26450,-0.26450,0.25670,2,2.000,1.0,-0.52120,-0.007848

In [5]:
ab_1A8_ref = pd.merge(
    ab_1A8,
    map,
    left_on=['site'],
    right_on=['reference_site']
)[[ 'sequential_site', 'wildtype', 'mutant', 'escape_mean', 'chain']].rename(
    columns={'sequential_site' : 'site'}
)

ab_1A8_ref.to_csv('H7_ab_1A8.csv')